PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT
?propertyURI
(group_concat(distinct ?rdfType; separator=", ") as ?types)
(group_concat(distinct ?propertyCollection; separator=", ") as ?propertyCollections)
(group_concat(distinct ?propertyCollectionLabel; separator=", ") as ?propertyCollectionLabels)
(group_concat(distinct ?propertyType; separator=", ") as ?propertyTypes)
(group_concat(distinct ?skosDefinition; separator=", ") as ?skosDefinitions)
(group_concat(distinct ?editorialNote; separator=", ") as ?editorialNotes)
(group_concat(distinct ?example; separator=", ") as ?examples)
(group_concat(distinct ?historyNote; separator=", ") as ?historyNotes)
(group_concat(distinct ?scopeNote; separator=", ") as ?scopeNotes)
(group_concat(distinct ?notation; separator=", ") as ?notations)
(group_concat(distinct ?label; separator=", ") as ?labels)

FROM <http://publications.europa.eu/resources/authority/lam/DocumentProperty>

{
  ?propertyURI a skos:Concept .
  optional {
    ?propertyURI rdf:type ?rdfType .
  }
  optional {
    ?propertyCollection skos:member ?propertyURI .
  }
  optional {
    ?propertyCollection skos:prefLabel ?propertyCollectionLabel . # same issue as for CELEX ?
  }
  optional {
    ?propertyURI dct:type ?propertyType .
  }
  optional {
    ?propertyURI skos:definition ?skosDefinition
  }
  optional {
      ?propertyURI skos:editorialNote ?editorialNote
  }
  optional {
      ?propertyURI skos:example ?example
  }
  optional {
      ?propertyURI skos:historyNote ?historyNote
  }
  optional {
      ?propertyURI skos:scopeNote ?scopeNote
  }
  optional {
    ?propertyURI skos:notation ?notation .
  }
  optional {
    ?propertyURI skos:prefLabel | skos:altLabel ?label.
  }
}
group by
?propertyURI