PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT
?propertyURI
(group_concat(distinct ?rdfType; separator=", ") as ?types)
(group_concat(distinct ?label; separator=", ") as ?labels)
(group_concat(distinct ?note; separator=", ") as ?notes)
(group_concat(distinct ?example; separator=", ") as ?examples)
(group_concat(distinct ?historyNote; separator=", ") as ?historyNotes)
(group_concat(distinct ?scopeNote; separator=", ") as ?scopeNotes)
(group_concat(distinct ?definition; separator=", ") as ?definitions)
(group_concat(distinct ?propertyCollection; separator=", ") as ?memberOf)
(group_concat(distinct ?memberOfLabel; separator=", ") as ?memberOfLabels)
{
  ?propertyURI a skos:Concept .
  optional {
    ?propertyURI rdf:type ?rdfType .
  }
  optional {
    ?propertyURI skos:prefLabel | skos:altLabel ?label .
  }
  optional {
    ?propertyURI skos:editorialNote ?note .
  }
  optional {
    ?propertyURI skos:definition ?definition .
  }
  optional {
    ?propertyURI skos:scopeNote ?scopeNote .
  }
  optional {
    ?propertyURI skos:historyNote ?historyNote .
  }
  optional {
    ?propertyURI skos:example ?example .
  }
  optional {
    ?propertyCollection skos:member ?propertyURI .
  }
  optional {
    ?propertyCollection skos:prefLabel ?memberOfLabel . # same issue as for CELEX ?
  }
}
group by
?propertyURI