openapi: 3.0.1

info:
  title: LAM 2 DOC Service
  description: |
    This API provides the possibility to <description needed>.

  contact:
    name: Eugeniu Costetchi
    url: http://costezki.ro
    email: costezki.eugen@gmail.com
  license:
    name: GNU General Public License Version 3 (GPLv3)
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.1

#servers:
#  - url: 'http://localhost:5000/'
#    description: Default server

components:
  parameters:
    exampleParam:
      in: query
      name: exampleParam
      required: false
      schema:
        type: string
      description: Example parameter
  schemas:
    LAM_PROPERTIES:
      type: object
      description: The LAM properties document.
      properties:
        lam_properties_document:
          type: string
          format: binary
          description: The LAM properties document.
    LAM_CLASSES:
      type: object
      description: The LAM classes document.
      properties:
        lam_classes_document:
          type: string
          format: binary
          description: The LAM classes document.
    CELEX_CLASSES:
      type: object
      description: The CELEX classes document.
      properties:
        celex_classes_document:
          type: string
          format: binary
          description: The CELEX classes document.


paths:
  /generate-report:
    get:
      operationId: lam4doc.entrypoints.api.handlers.generate_lam_report
      description: Endpoint to generate the LAM report.
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.

  /upload-rdf:
    post:
      operationId: lam4doc.entrypoints.api.handlers.upload_rdfs
      description: Endpoint to upload RDF files.
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              anyOf:
                - $ref: '#/components/schemas/LAM_PROPERTIES'
                - $ref: '#/components/schemas/LAM_CLASSES'
                - $ref: '#/components/schemas/CELEX_CLASSES'
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.

