openapi: 3.0.1

info:
  title: LAM 2 DOC Service
  description: |
    This API provides the possibility to <description needed>.

  contact:
    name: Eugeniu Costetchi
    url: http://costezki.ro
    email: costezki.eugen@gmail.com
  license:
    name: GNU General Public License Version 3 (GPLv3)
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.1

servers:
  - url: 'http://localhost:4050/'
    description: Default server

components:
  parameters:
    extensionParam:
      in: query
      name: report_extension
      required: false
      schema:
        type: string
      description: Report type to be returned
  schemas:
    UPLOAD_SCHEMA:
      type: object
      description: The LAM properties document.
      properties:
        lam_properties_document:
          type: string
          format: binary
          description: The LAM properties document.
        lam_classes_document:
          type: string
          format: binary
          description: The LAM classes document.
        celex_classes_document:
          type: string
          format: binary
          description: The CELEX classes document.
        dataset_name:
          type: string
      required:
        - dataset_name

paths:
  /generate-report:
    get:
      operationId: lam4doc.entrypoints.api.handlers.generate_lam_report
      description: Endpoint to generate the LAM report.
      parameters:
        - $ref: '#/components/parameters/extensionParam'
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.
  /generate-indexes:
    get:
      operationId: lam4doc.entrypoints.api.handlers.generate_indexes
      description: Endpoint to generate the LAM indexes.
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.
  /lam-files:
    get:
      operationId: lam4doc.entrypoints.api.handlers.get_lam_files
      description: Endpoint to generate all LAM files.
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.
  /upload-rdf:
    post:
      operationId: lam4doc.entrypoints.api.handlers.upload_rdfs
      description: Endpoint to upload RDF files.
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UPLOAD_SCHEMA'
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.