name: test

on:
  push:
    branches:  [ '**' ]

jobs:
  main:
    name: main
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8

    - name: Spin up the ui, api
      run: |
        make build-services && make start-services

    - name: Install dependencies
      run: |
        make install-dev

    - name: Test with pytest
      run: |
        make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
